### ISSUE TITLE
Error when getting token

### ISSUE THREAD

**Issue by dmadams** [LassoProject/lasso#20]
After receiving the id token Lasso is failing with the following error.

Logs:

`time="2018-09-07T18:11:26Z" level=info msg="OpenID userinfo body:  {\"sub\":\"*************************"}\r\n"
time="2018-09-07T18:11:26Z" level=debug msg="{  0 0 0}"
time="2018-09-07T18:11:26Z" level=debug msg="no domains configured"
time="2018-09-07T18:11:26Z" level=error msg="no bucket for users"
time="2018-09-07T18:11:26Z" level=debug msg="new user.. setting created on to 1536343886"
time="2018-09-07T18:11:26Z" level=error msg="key required"
time="2018-09-07T18:11:26Z" level=debug msg="token: &{ 0xc4201381c0 map[typ:JWT alg:HS256] { [] { 1536373886  0 Lasso 0 }}  false}"
time="2018-09-07T18:11:26Z" level=debug msg="token expires: 1536373886"
time="2018-09-07T18:11:26Z" level=debug msg="diff from now: 30000"
time="2018-09-07T18:11:26Z" level=debug msg="compressed string: H4sIAAAAAAAA_xzMwY6CMBRA0S8aMsOIkaUC4nuhJQGF4o7WRgpUKy6g_XqD25ubIy12PBUqVwgXB39UwRseRSAi2MJgWBVh6EmLI6-Phq_xO1BzSysHveGsnNWVdTP0z4WeiU-ccHl897MIjfgnK0waRh23GHqnn7HIgsQesGPaDS1N6ric9X6SRDcSmqnavFq91Lvl9xMAAP__MX4AgpkAAAA="
2018/09/07 18:11:26 http: panic serving 192.168.0.2:34052: interface conversion: interface {} is nil, not string
goroutine 62 [running]:
net/http.(*conn).serve.func1(0xc4200d3720)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x8da480, 0xc42004f000)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/dmadams/lasso/handlers.CallbackHandler(0xb8b580, 0xc4201089a0, 0xc4201b4600)
        /go/src/github.com/dmadams/lasso/handlers/handlers.go:415 +0xa3b
net/http.HandlerFunc.ServeHTTP(0x97a408, 0xb8b580, 0xc4201089a0, 0xc4201b4600)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/dmadams/lasso/pkg/timelog.TimeLog.func1(0xb8b580, 0xc4201089a0, 0xc4201b4400)
        /go/src/github.com/dmadams/lasso/pkg/timelog/timelog.go:33 +0x14b
net/http.HandlerFunc.ServeHTTP(0xc42000c540, 0xb8b580, 0xc4201089a0, 0xc4201b4400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201463c0, 0xb8b580, 0xc4201089a0, 0xc4201b4400)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420162000, 0xb8b580, 0xc4201089a0, 0xc4201b4400)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200d3720, 0xb8bd80, 0xc4201ca080)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce`
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce`

**Comment by bnfinet** [comment]
It would appear "no domains configured" is the issue.  Can you offer your configuration via hastebin?

**Comment by bnfinet** [comment]
@dmadams were you able to resolve the issue?
